const STORAGE_KEY = 'jugyo-kanri-public-v1';
const defaultSubjects = [];
const defaultCategories = [{id:'school',name:'学校行事',color:'#0f766e'},{id:'meeting',name:'会議・研修',color:'#d97706'},{id:'exam',name:'テスト・評価',color:'#c2413b'}];
const firstDate = new Date();
const firstDateKey = `${firstDate.getFullYear()}-${String(firstDate.getMonth()+1).padStart(2,'0')}-${String(firstDate.getDate()).padStart(2,'0')}`;
const initial = {year:firstDate.getFullYear(),weekStart:firstDateKey,selectedDate:firstDateKey,lessons:[],subjects:[],categories:defaultCategories.map(x=>({...x})),events:[]};
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || initial;
let editingId = null;
const $ = (s) => document.querySelector(s);
const fmt = (d, opts={month:'long',day:'numeric',weekday:'short'}) => new Intl.DateTimeFormat('ja-JP',opts).format(new Date(d+'T00:00:00'));
const key = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function addDays(date,n){const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+n);return key(d)}
function monday(date){const d=new Date(date+'T00:00:00');const x=(d.getDay()+6)%7;d.setDate(d.getDate()-x);return key(d)}
function subjectNames(){return state.subjects.map(s=>s.name)}
function normalizeState(){const saved=state.subjects?.map(s=>typeof s==='string'?{id:s,name:s}:s)||[];const used=[...new Set(state.lessons.map(x=>x.subject))];state.subjects=[...saved,...used.filter(name=>!saved.some(s=>s.name===name)).map(name=>({id:name,name}))];if(!state.subjects.length)state.subjects=defaultSubjects.map(name=>({id:name,name}));if(!Array.isArray(state.categories)||!state.categories.length)state.categories=defaultCategories.map(x=>({...x}));state.events=state.events.map(e=>({...e,categoryId:e.categoryId||'school'}));if(!Array.isArray(state.templates))state.templates=[];}
function updateWelcome(){const card=$('#welcome-card');if(card)card.hidden=Boolean(state.welcomeDismissed||state.subjects.length)}
function categoryFor(id){return state.categories.find(c=>c.id===id)||state.categories[0]}
function fiscalRange(){return {start:`${state.year}-04-01`,end:`${Number(state.year)+1}-03-31`}}
function activeRange(){return state.reportRange?.start&&state.reportRange?.end?state.reportRange:fiscalRange()}
function show(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));$('#'+screen).classList.add('active');document.querySelector(`[data-screen="${screen}"]`).classList.add('active');$('#page-title').textContent=screen==='week-screen'?'今週の授業':screen==='dashboard-screen'?'年間授業時数':'カレンダー';if(screen==='week-screen')updateWelcome();if(screen==='dashboard-screen')renderDashboard();if(screen==='calendar-screen')renderCalendar();}
function renderWeek(){const start=monday(state.weekStart);state.weekStart=start;const grid=$('#week-grid');grid.innerHTML='<div class="time-head">時限</div>'+Array.from({length:5},(_,i)=>{const d=addDays(start,i),today=key(new Date())===d;return `<div class="day-head ${today?'today':''}"><b>${fmt(d,{day:'numeric'})}</b><span>${['月','火','水','木','金'][i]}</span></div>`}).join('');for(let p=1;p<=6;p++){grid.insertAdjacentHTML('beforeend',`<div class="period">${p}</div>`);for(let i=0;i<5;i++){const date=addDays(start,i),lesson=state.lessons.find(x=>x.date===date&&Number(x.period)===p);grid.insertAdjacentHTML('beforeend',lesson?`<button class="lesson-card" data-id="${lesson.id}"><span class="subject">${lesson.subject}</span><span class="content">${lesson.content||'（内容未入力）'}</span>${lesson.room?`<span class="room">${lesson.room}</span>`:''}<i class="status ${lesson.status}"></i></button>`:`<button class="lesson-card empty" data-date="${date}" data-period="${p}" aria-label="${fmt(date)} ${p}時間目に授業を追加">＋</button>`);}}$('#week-label').textContent=`${fmt(start)}〜${fmt(addDays(start,4))}`;}
function renderTemplates(){const list=$('#template-list');list.innerHTML=state.templates.length?state.templates.map(t=>`<div class="template-row"><div><b>${t.name}</b><small>${t.slots.length} 時限を登録</small></div><div class="template-actions"><button type="button" class="apply-template" data-apply-template="${t.id}">この週へ適用</button><button type="button" class="delete-template" data-delete-template="${t.id}">削除</button></div></div>`).join(''):'<p class="form-note">保存済みのテンプレートはありません。</p>';}
function applyTemplate(id){const template=state.templates.find(t=>t.id===id);if(!template)return;const start=monday(state.weekStart);let added=0,skipped=0;template.slots.forEach((slot,index)=>{const date=addDays(start,slot.dayIndex);if(state.lessons.some(l=>l.date===date&&Number(l.period)===Number(slot.period))){skipped++;return}state.lessons.push({id:String(Date.now()+index),date,period:Number(slot.period),subject:slot.subject,content:'',room:slot.room||'',status:'planned'});added++});save();renderWeek();renderDashboard();$('#template-dialog').close();alert(`${added}件の授業を追加しました。既存の授業 ${skipped}件は変更していません。`);}
function renderDashboard(){const done=state.lessons.filter(x=>x.status==='done');const range=activeRange();const within=done.filter(x=>x.date>=range.start&&x.date<=range.end),scheduled=state.lessons.filter(x=>x.date>=range.start&&x.date<=range.end&&x.status!=='cancelled'),rate=scheduled.length?Math.round(within.length/scheduled.length*100):0,angle=rate*3.6;$('#range-start').value=range.start;$('#range-end').value=range.end;$('#year-progress').textContent=`${within.length}時間`;$('#year-summary').textContent=`${fmt(range.start,{year:'numeric',month:'long',day:'numeric'})}〜${fmt(range.end,{year:'numeric',month:'long',day:'numeric'})}`;$('#progress-donut').style.background=`conic-gradient(#fff 0deg ${angle}deg,#ffffff55 ${angle}deg 360deg)`;$('#progress-donut').querySelector('span').textContent=`${rate}%`;$('#progress-list').innerHTML=subjectNames().map(s=>{const n=within.filter(x=>x.subject===s).length;return `<article class="progress-card"><div class="progress-top"><b>${s}</b><span>実施 ${n}時間</span></div><div class="progress-meta"><span>指定期間内の実施済み授業</span><span>${n===0?'未実施':'記録済み'}</span></div></article>`}).join('');$('#attention-count').textContent='';$('#subject-settings').innerHTML=state.subjects.map(s=>`<div class="subject-setting"><span>${s.name}</span><button data-delete-subject="${s.id}">削除</button></div>`).join('');}
function renderCalendar(){const current=new Date(state.selectedDate+'T00:00:00'), first=new Date(current.getFullYear(),current.getMonth(),1), start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));const y=current.getFullYear(),m=current.getMonth();$('#month-label').textContent=`${y}年${m+1}月`;$('#calendar-grid').innerHTML=Array.from({length:42},(_,i)=>{const d=key(new Date(start.getFullYear(),start.getMonth(),start.getDate()+i)),outside=new Date(d+'T00:00:00').getMonth()!==m,events=state.events.filter(e=>e.date===d),dots=[...new Map(events.map(e=>{const c=categoryFor(e.categoryId);return [c.id,c]})).values()].map(c=>`<i style="background:${c.color}"></i>`).join(''),labels=events.slice(0,2).map(e=>{const c=categoryFor(e.categoryId);return `<span class="calendar-event-label" style="--event-color:${c.color}">${e.title}</span>`}).join(''),more=events.length>2?`<span class="calendar-event-more">＋${events.length-2}件</span>`:'';return `<button class="calendar-day ${outside?'outside':''} ${d===state.selectedDate?'selected':''}" data-caldate="${d}" aria-label="${fmt(d)} ${events.map(e=>e.title).join('、')}"><b>${new Date(d+'T00:00:00').getDate()}</b>${labels}${more}${dots?`<span class="calendar-dots">${dots}</span>`:''}</button>`}).join('');const events=state.events.filter(e=>e.date===state.selectedDate);$('#event-date').textContent=fmt(state.selectedDate);$('#event-list').innerHTML=events.length?events.map(e=>{const c=categoryFor(e.categoryId);return `<div class="event-item"><i class="event-color" style="background:${c.color}"></i><span>${e.title}</span><span class="impact">${c.name}</span></div>`}).join(''):'<div class="event-item">登録されている行事はありません。</div>';}
function openLesson(lesson,date,period){const names=subjectNames();if(!lesson&&!names.length){alert('先に「年間時数」画面で科目・学級を追加してください。');show('dashboard-screen');return}editingId=lesson?.id||null;$('#dialog-title').textContent=lesson?'授業を編集':'授業を追加';$('#lesson-date').value=lesson?.date||date;$('#lesson-period').value=lesson?.period||period||1;$('#lesson-subject').innerHTML=names.map(s=>`<option ${s===(lesson?.subject||names[0])?'selected':''}>${s}</option>`).join('');$('#lesson-content').value=lesson?.content||'';$('#lesson-room').value=lesson?.room||'';$('#lesson-status').value=lesson?.status||'planned';$('#delete-lesson').style.visibility=lesson?'visible':'hidden';$('#duplicate-lesson').style.visibility=lesson?'visible':'hidden';$('#lesson-dialog').showModal();}
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav)show(nav.dataset.screen);const card=e.target.closest('.lesson-card');if(card){const lesson=state.lessons.find(x=>x.id===card.dataset.id);openLesson(lesson,card.dataset.date,card.dataset.period)}const day=e.target.closest('[data-caldate]');if(day){state.selectedDate=day.dataset.caldate;save();renderCalendar();}});
$('#previous-week').onclick=()=>{state.weekStart=addDays(state.weekStart,-7);save();renderWeek()};$('#next-week').onclick=()=>{state.weekStart=addDays(state.weekStart,7);save();renderWeek()};$('#add-lesson').onclick=()=>openLesson(null,state.weekStart,1);
$('#open-templates').onclick=()=>{renderTemplates();$('#template-dialog').showModal()};$('#save-template').onclick=()=>{const name=$('#template-name').value.trim(),start=monday(state.weekStart);if(!name){alert('テンプレート名を入力してください。');return}if(state.templates.some(t=>t.name===name)){alert('同じテンプレート名が登録されています。');return}const slots=state.lessons.filter(l=>l.date>=start&&l.date<=addDays(start,4)).map(l=>({dayIndex:Math.round((new Date(l.date+'T00:00:00')-new Date(start+'T00:00:00'))/86400000),period:Number(l.period),subject:l.subject,room:l.room||''}));if(!slots.length){alert('保存する授業がありません。先に週時間割を入力してください。');return}state.templates.push({id:String(Date.now()),name,slots});save();$('#template-name').value='';renderTemplates();};document.addEventListener('click',e=>{const apply=e.target.closest('[data-apply-template]');if(apply){applyTemplate(apply.dataset.applyTemplate);return}const remove=e.target.closest('[data-delete-template]');if(remove){state.templates=state.templates.filter(t=>t.id!==remove.dataset.deleteTemplate);save();renderTemplates();}});
$('#lesson-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();const data={id:editingId||String(Date.now()),date:$('#lesson-date').value,period:Number($('#lesson-period').value),subject:$('#lesson-subject').value,content:$('#lesson-content').value.trim(),room:$('#lesson-room').value.trim(),status:$('#lesson-status').value};if(state.lessons.some(x=>x.id!==editingId&&x.date===data.date&&Number(x.period)===data.period)){alert('この日時にはすでに授業が登録されています。日付または時限を変更してください。');return}state.lessons=editingId?state.lessons.map(x=>x.id===editingId?data:x):[...state.lessons,data];state.weekStart=monday(data.date);save();$('#lesson-dialog').close();renderWeek();renderDashboard();});
$('#delete-lesson').onclick=()=>{state.lessons=state.lessons.filter(x=>x.id!==editingId);save();$('#lesson-dialog').close();renderWeek();renderDashboard();};
$('#duplicate-lesson').onclick=()=>{editingId=null;$('#dialog-title').textContent='授業を複製';$('#delete-lesson').style.visibility='hidden';$('#duplicate-lesson').style.visibility='hidden';alert('複製先の日付・時限を選んで保存してください。');};
document.querySelectorAll('[data-print-view]').forEach(button=>button.onclick=()=>window.print());
$('#previous-month').onclick=()=>{const d=new Date(state.selectedDate+'T00:00:00');d.setMonth(d.getMonth()-1);state.selectedDate=key(d);save();renderCalendar()};$('#next-month').onclick=()=>{const d=new Date(state.selectedDate+'T00:00:00');d.setMonth(d.getMonth()+1);state.selectedDate=key(d);save();renderCalendar()};
$('#add-event').onclick=()=>{$('#event-input-date').value=state.selectedDate;$('#event-category').innerHTML=state.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');$('#event-dialog').showModal()};$('#event-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();state.events.push({id:String(Date.now()),date:$('#event-input-date').value,title:$('#event-title').value,categoryId:$('#event-category').value});state.selectedDate=$('#event-input-date').value;save();$('#event-dialog').close();renderCalendar();});
$('#add-subject').onclick=()=>{$('#subject-name').value='';$('#subject-dialog').showModal()};$('#subject-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();const name=$('#subject-name').value.trim();if(state.subjects.some(s=>s.name===name)){alert('同じ名称が登録されています。');return}state.subjects.push({id:String(Date.now()),name});save();$('#subject-dialog').close();renderDashboard();updateWelcome();});
$('#dismiss-welcome').onclick=()=>{state.welcomeDismissed=true;save();updateWelcome();};
function updateRange(){const start=$('#range-start').value,end=$('#range-end').value;if(!start||!end)return;if(start>end){alert('終了日は開始日以降の日付を選択してください。');renderDashboard();return}state.reportRange={start,end};save();renderDashboard();}$('#range-start').onchange=updateRange;$('#range-end').onchange=updateRange;$('#reset-range').onclick=()=>{state.reportRange=fiscalRange();save();renderDashboard();};
document.addEventListener('click',e=>{const remove=e.target.closest('[data-delete-subject]');if(!remove)return;const subject=state.subjects.find(s=>s.id===remove.dataset.deleteSubject);if(state.lessons.some(x=>x.subject===subject.name)){alert('この科目・学級は授業記録で使用中のため削除できません。');return}state.subjects=state.subjects.filter(s=>s.id!==subject.id);save();renderDashboard();updateWelcome();});
function renderCategorySettings(){ $('#category-list').innerHTML=state.categories.map(c=>`<div class="category-row"><input type="color" data-category-color="${c.id}" value="${c.color}"><input data-category-name="${c.id}" value="${c.name}" maxlength="16"><button type="button" data-delete-category="${c.id}">削除</button></div>`).join('');}
$('#settings-button').onclick=()=>{$('#setting-year').value=state.year;$('#settings-dialog').showModal()};$('#settings-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();state.year=$('#setting-year').value;save();$('#school-year').textContent=`令和${Number(state.year)-2018}年度`;$('#settings-dialog').close();});
$('#open-category-settings').onclick=()=>{renderCategorySettings();$('#category-dialog').showModal()};$('#add-category').onclick=()=>{const name=$('#category-name').value.trim(),color=$('#category-color').value;if(!name){alert('カテゴリー名を入力してください。');return}if(state.categories.some(c=>c.name===name)){alert('同じカテゴリー名が登録されています。');return}state.categories.push({id:String(Date.now()),name,color});$('#category-name').value='';renderCategorySettings();};$('#category-list').onclick=e=>{const button=e.target.closest('[data-delete-category]');if(!button)return;const id=button.dataset.deleteCategory;if(state.events.some(x=>x.categoryId===id)){alert('このカテゴリーを使った行事があるため削除できません。');return}state.categories=state.categories.filter(c=>c.id!==id);renderCategorySettings();};$('#category-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();state.categories=state.categories.map(c=>({id:c.id,name:document.querySelector(`[data-category-name="${c.id}"]`).value.trim()||c.name,color:document.querySelector(`[data-category-color="${c.id}"]`).value}));save();$('#category-dialog').close();renderCalendar();});
async function exportBackup(){const filename=`授業管理_${state.year}_backup.json`,file=new File([JSON.stringify(state,null,2)],filename,{type:'application/json'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'授業管理のバックアップ',text:'バックアップファイルを保存します。',files:[file]});return}}catch(error){if(error.name==='AbortError')return}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=filename;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},1000)}$('#export-data').onclick=exportBackup;$('#import-data').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);normalizeState();save();renderWeek();renderDashboard();renderCalendar();updateWelcome();$('#settings-dialog').close();alert('バックアップを復元しました。')}catch{alert('バックアップを読み込めませんでした。')}};r.readAsText(f)};
normalizeState();save();$('#school-year').textContent=`令和${state.year-2018}年度`;updateWelcome();renderWeek();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
